### ISSUE TITLE
Fix the size constraint of anime and manga thumbnail pictures

### ISSUE THREAD

**Issue by mhaidarhanif** [amadzuki/saikou-client#11]
Have to fix the ratio constraint of anime and manga thumbnail pictures, so it won't looks compressed.

CSS `object-fit` property could solve it. https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

The height can be the same, but the ratio should be fixed.

Original:
<img width="424" alt="Screenshot 2020-07-15 at 20 33 30" src="https://user-images.githubusercontent.com/235584/87551373-7406e300-c6da-11ea-8cd2-107202df0126.png">
(400×636)

Currently:
<img width="220" alt="Screenshot 2020-07-15 at 20 33 38" src="https://user-images.githubusercontent.com/235584/87551390-78cb9700-c6da-11ea-9ab2-052182fba0ae.png">
(200×280)

**Comment by mhaidarhanif** [comment]
@amadzuki You can see something wrong with Senku's head. 😂

**Comment by amadzuki** [comment]
Fix the size to 215 x 340
