### ISSUE TITLE
Implement nesting router for ProductDetail

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/saikou-client#13]
I decided to make `Anime` and `Manga` page into one page component because of the similarity (for now), I named it `ProductDetail`.

I choose the word `product` to represent anime and manga (and for future type piece of work such as manghwa, tokusatsu, etc.). I think the word `sakuhin` is also can represent them. But then I think using English should be better. The cons is just the word `product` can be mistaken as something to be sold (after all, this isn't an e-commerce site).

What do you think, @mhaidarh ?

**Comment by amadzuki** [comment]
I also plan to make the route rely on the `id` of the product instead of the name (slug). Just as we've discussed before.

**Comment by mhaidarhanif** [comment]
Let's use Item instead of Product.

**Comment by amadzuki** [comment]
Done changing the term `product` to `item`
