### ISSUE TITLE
Change page title dynamically based on anime or manga title

### ISSUE THREAD

**Issue by mhaidarhanif** [amadzuki/saikou-client#17]
Can use [React Helmet](https://github.com/nfl/react-helmet).

Covered here:

https://www.notion.so/azobu/React-with-SEO-and-Metadata-1bf58f4ef4114bb29fee2e0cb24f61fe

Compare side-by-side:

<img width="377" alt="Screenshot 2020-07-18 at 18 39 15" src="https://user-images.githubusercontent.com/235584/87851749-03ec9d00-c926-11ea-8d29-033071aabecf.png">

<img width="320" alt="Screenshot 2020-07-18 at 18 39 07" src="https://user-images.githubusercontent.com/235584/87851746-00f1ac80-c926-11ea-8b57-b6ac80909bea.png">

**Comment by amadzuki** [comment]
Alright, will do

**Comment by amadzuki** [comment]
Done Implemented.

I've used `{page-title} | Saikou` convention. Is that acceptable @mhaidarh ?
