### ISSUE TITLE
Deploy Saikou client

### ISSUE THREAD

**Issue by mhaidarhanif** [amadzuki/saikou-client#2]
Deploy Saikou client to Netlify.

Remember to setup the `_redirects` file.

https://www.netlify.com/blog/2016/07/22/deploy-react-apps-in-less-than-30-seconds

**Comment by amadzuki** [comment]
Done Sir @mhaidarh 

Thanks for the `_redirects` reference

**Comment by mhaidarhanif** [comment]
@amadzuki You're welcome sir
