### ISSUE TITLE
Refactor redux code structure

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/saikou-client#35]
Create redux directory in src with store, actions and reducers as sub-directory. And then refactor the code accordingly.

**Comment by mhaidarhanif** [comment]
@amadzuki I've made a template repo related to this: https://github.com/azobu-projects/template-web

You can check how now I structure the Redux configuration: https://github.com/azobu-projects/template-web/blob/master/src/redux/store/index.js

There are several ceremonies though, but it can train you to read realistic company code in the upcoming job.
