### ISSUE TITLE
Implement favorite button in ItemDetail

### ISSUE THREAD

**Issue by amadzuki** [amadzuki/saikou-client#37]
The button can toggle favorited true or false and send the item id to favoritedAnime/favoritedManga array in user state redux

**Comment by amadzuki** [comment]
It's supposed to update user data in the server too. I'll do that later while implementing thunk.

**Comment by mhaidarhanif** [comment]
@amadzuki Yes you can use an action thunk to request for favorite an item/anime/manga.
